### ISSUE TITLE
Grapher not showing up

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#241] opened 2016-07-22 22:34 UTC
On matrix-reloaded (on server v1.1.0, client v1.1.0.0-g280f46b), none of the data vault directory structure shows up on the grapher tab. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/8183919/17072994/9abf2342-5021-11e6-9bfb-626bd350510f.png)

If I instead use a prior version (server/client both v1.0.1-7-g0c80392), the full data vault directory shows up.

**Comment by adamcw** [comment] 2016-07-22 22:39
@maffoo @joshmutus Is this due to the latest ansible changes?

If it's code related, can someone get me the password to matrix-reloaded so I can inspect the page.

**Comment by maffoo** [comment] 2016-07-22 22:45
@jwenner, it works fine for me. Have you tried hard refreshing the page (Ctrl-Shift-R)? Also, do you see any errors in the log in the developer tools?

**Comment by joshm-3b6b58** [comment] 2016-07-22 22:48
@jwenner Are you viewing through remote desktop?

**Comment by adamcw** [comment] 2016-07-22 22:48
@joshmutus Remote desktop shouldn't break the directory view, only potentially the view of the actual plots.

**Comment by jwenner** [comment] 2016-07-22 22:49
Even with this hard refresh, the data vault still doesn't show up. I am not viewing though remote desktop. The URL is https://matrix-reloaded.physics.ucsb.edu:7443/trench/grapher/.

**Comment by joshm-3b6b58** [comment] 2016-07-22 22:50
Can you check if webGL is running? 

Can you follow these steps?
Step 1: Open Google Chrome
Step 2: Type chrome://flags in the address bar
Step 3: Press Ctrl + f and type ” Rendering list “, “Override software rendering list” should come up, >Now click on Enable and restart the browser.

**Comment by jwenner** [comment] 2016-07-22 22:51
> Also, do you see any errors in the log in the developer tools?

Is this the correct screen? If so, it looks like only deprecation warnings.
![image](https://cloud.githubusercontent.com/assets/8183919/17073258/04555ab8-5024-11e6-9db9-1fed45917c3b.png)

**Comment by adamcw** [comment] 2016-07-22 22:52
@joshmutus This isn't a WebGL problem, this page doesn't render any WebGL.

@maffoo I can confirm that the page loads just fine for me and I'm able to navigate to graphs.

@jwenner That error console looks just fine... very strange... have you tried closing the browser entirely?

**Comment by jwenner** [comment] 2016-07-22 22:53
@joshmutus, once I enabled that "Override software rendering list" and restarted the browser, it now shows up.

**Comment by adamcw** [comment] 2016-07-22 22:53
@jwenner Can you disable it again, restart, and see if it breaks again?

**Comment by jwenner** [comment] 2016-07-22 22:54
Once I go back to disabling "Override software rendering list" and restart, the data vault directory still shows up

**Comment by jwenner** [comment] 2016-07-22 22:54
So, looks like indeed a full restart of the browser was what was needed. Thanks, all!

**Comment by adamcw** [comment] 2016-07-22 22:55
Good, I was going to be very confused if the flag fixed anything. Would have needed further investigation. Glad this was easily fixed.

**Closed as completed by adamcw** 2016-07-22 22:55 UTC
Labels: bug
