### ISSUE TITLE
Make expandable dialog dynamically sized

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#47] opened 2015-09-21 20:08 UTC
THe truncated text is a fixed length now and should be sized to fit the lenght of a single line of text

**Comment by maffoo** [comment] 2015-09-21 21:23
It should be possible to do this purely in CSS, without needing to do any work in javascript to make a separate `valueShort` property or update the `cols` property (see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)). I've put up a branch trying to do this ([u/maffoo/css-ellipsis](https://github.com/labrad/scalabrad-web/tree/u/maffoo/css-ellipsis)), but it doesn't seem to show the ellipsis as expected in my version of chrome. Feel free to take a look.

**Comment by joshm-3b6b58** [comment] 2015-09-21 21:30
I really like that solution. I just checked out the branch, but I don't see any ellipsis on my end.

**Comment by maffoo** [comment] 2015-09-21 21:34
Yeah, same problem for me. If you look at the MDN page I linked to, they have a "live result" column in the table showing what your browser actually does. For me, the `text-overflow: ellipsis` row works, but the others just show the text being truncated. So it looks like chrome is a bit picky about things, but it should work. Might be something going on with this being a polymer element, or the fact that there is a hidden textarea in there or who knows what. _C'est la vie_ on the web...

**Comment by joshm-3b6b58** [comment] 2015-09-21 21:38
Speaking of Chrome, did you see this: https://github.com/szhu/3030/tree/master ?

**Comment by maffoo** [comment] 2015-09-21 21:54
LOL; that's a crazy bug.

**Comment by joshm-3b6b58** [comment] 2015-09-21 21:58
I can get the elipsis to sort of work when it's just in a div, but only when I set the width to 90%, but it stops working when I draw the window smaller than a certain size. I suspect that the width of the member relative to the table is the problem and the elipsis is rendering off screen? Do you mind if I push to this branch so you can take a look?

**Comment by maffoo** [comment] 2015-09-21 22:05
feel free to push the the branch

**Comment by joshm-3b6b58** [comment] 2015-09-21 22:08
OK check it out. For me the elipsises work, until I make the window smaller than a certain size, then the table stops shrinking and it doesn't really work. Does it work for you?

**Comment by joshm-3b6b58** [comment] 2015-09-21 22:32
Also, how come I don't show up as a contributor to this repository?

**Comment by maffoo** [comment] 2015-09-21 22:39
You need to associate joshmutus@google.com with your github account. It seems that's email in the commits you're making and github doesn't recognize it.

**Comment by joshm-3b6b58** [comment] 2015-09-21 22:44
ah cool. Thanks

**Comment by joshm-3b6b58** [comment] 2015-09-21 23:05
Did that branch look OK to you?

**Comment by maffoo** [comment] 2015-09-21 23:11
I think the problem is with the table cell formatting. It seems that divs are normally sized from the outside by fitting themselves to their containing boxes, while table cells are sized from the inside by fitting themselves to their contents. So the table cells just grow and the text doesn't know it's overflowing, unless you give the text elements themselves a size. I guess there are ways to make table cells behave more like regular divs to get this to work, but it's not clear what the right thing to do is. One possibility is to put a div or span immediately inside the table cell to make it work more like div formatting (see [this example](http://jsfiddle.net/maruxa1j/)). Feel free to experiment with this.

**Comment by adamcw** [comment] 2016-07-25 22:56
@maffoo @joshmutus Did this ever get resolved? The branch mentioned doesn't exist anymore. It's also unclear from the report exactly what text is desired to have the proper overflowing.

**Comment by maffoo** [comment] 2016-07-25 22:59
I think we can close this. There's still some awkwardness with the key edit dialog (in particular, if you paste in a large value from the clipboard, it doesn't resize), but we can file separate issues for those things with more clear descriptions.

**Closed as completed** 2016-07-25 22:59 UTC
